"use client";

// Direct uploads (generated by `gemstack add storage`): the file goes from the
// browser straight to storage (S3, or the Ruby disk endpoint in development).
//
//   const { signedId } = await uploadFile(file, { onProgress: (p) => setProgress(p) });
//   await products.update(id, { image: signedId });
import { useMutation } from "@tanstack/react-query";
import { uploads } from "@/lib/api/generated";

export interface UploadResult {
  /** Send this to the API to attach the file to a record. */
  signedId: string;
}

export interface UploadOptions {
  /** 0–1 while uploading. */
  onProgress?: (fraction: number) => void;
  signal?: AbortSignal;
}

export async function uploadFile(file: File, options: UploadOptions = {}): Promise<UploadResult> {
  const upload = await uploads.create({
    filename: file.name,
    content_type: file.type || "application/octet-stream",
    byte_size: file.size,
  });
  await send(upload.url, upload.method, upload.headers as Record<string, string>, file, options);
  return { signedId: upload.signed_id };
}

// XMLHttpRequest rather than fetch: it reports upload progress.
function send(url: string, method: string, headers: Record<string, string>, file: File, options: UploadOptions) {
  return new Promise<void>((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open(method, url);
    for (const [name, value] of Object.entries(headers)) xhr.setRequestHeader(name, value);
    xhr.upload.onprogress = (event) => {
      if (event.lengthComputable) options.onProgress?.(event.loaded / event.total);
    };
    xhr.onload = () => (xhr.status < 300 ? resolve() : reject(new Error(`Upload failed (HTTP ${xhr.status})`)));
    xhr.onerror = () => reject(new Error("Upload failed: network error"));
    xhr.onabort = () => reject(new DOMException("Upload aborted", "AbortError"));
    options.signal?.addEventListener("abort", () => xhr.abort());
    xhr.send(file);
  });
}

/** uploadFile as a TanStack Query mutation: const upload = useUpload(); upload.mutateAsync(file). */
export function useUpload(options: Omit<UploadOptions, "signal"> = {}) {
  return useMutation({ mutationFn: (file: File) => uploadFile(file, options) });
}
