# frozen_string_literal: true

require_relative "../test_helper"

# The authentication flows generated by `gemstack add auth`.
class AuthTest < GemStack::TestCase
  PASSWORD = "correct horse battery staple"

  def create_user(email = "ada@example.com") = User.create(email: email, password: PASSWORD)
  def token_from(mail) = mail.text_part.decoded[/token=([\w-]+)/, 1]

  def test_signup_signs_in_and_sends_a_verification_email
    assert_emails(1) { post_json "/api/auth/signup", { email: "Ada@Example.com", password: PASSWORD } }

    assert_status 201
    assert_equal "ada@example.com", json_body["email"]
    refute json_body.key?("password_digest")
    assert_equal ["ada@example.com"], last_email.to
    get_json "/api/auth/me"

    assert_status 200
  end

  def test_signup_validation
    create_user
    post_json "/api/auth/signup", { email: "ada@example.com", password: "short" }

    assert_error 422, "validation_failed"
    assert_equal ["is already taken"], json_body["errors"]["email"]
    assert_equal ["is too short (minimum 12 characters)"], json_body["errors"]["password"]
  end

  def test_login_me_logout
    user = create_user
    post_json "/api/auth/login", { email: "ADA@example.com", password: PASSWORD }

    assert_status 200
    get_json "/api/auth/me"

    assert_equal user.id, json_body["id"]
    delete_json "/api/auth/logout"

    assert_status 204
    get_json "/api/auth/me"

    assert_error 401, "unauthenticated"
  end

  def test_login_failures_look_the_same
    create_user
    post_json "/api/auth/login", { email: "ada@example.com", password: "wrong password!" }
    wrong_password = json_body
    post_json "/api/auth/login", { email: "nobody@example.com", password: PASSWORD }

    assert_error 401, "invalid_credentials"
    assert_equal wrong_password["error"]["message"], json_body["error"]["message"]
  end

  def test_password_reset
    user = create_user
    other_device = GemStack::Auth::Sessions.create(user.id)
    assert_emails(1) { post_json "/api/auth/password/forgot", { email: user.email } }

    assert_status 202
    post_json "/api/auth/password/reset", { token: token_from(last_email), password: "a brand new passphrase" }

    assert_status 200
    assert User.authenticate_by(email: user.email, password: "a brand new passphrase")
    assert_nil GemStack::Auth::Sessions.find(other_device), "other sessions end"
    post_json "/api/auth/password/reset", { token: token_from(last_email), password: "and another one!!" }

    assert_error 400, "invalid_token"
  end

  def test_forgot_password_does_not_reveal_accounts
    assert_emails(0) { post_json "/api/auth/password/forgot", { email: "nobody@example.com" } }

    assert_status 202
  end

  def test_email_verification
    user = create_user
    sign_in_as(user)
    assert_emails(1) { post_json "/api/auth/email/resend" }
    post_json "/api/auth/email/verify", { token: token_from(last_email) }

    assert_status 204
    assert User[user.id].email_verified?
  end

  def test_api_tokens
    user = create_user
    sign_in_as(user)
    post_json "/api/auth/tokens", { name: "CI" }

    assert_status 201
    token = json_body["token"]
    get_json "/api/auth/me", {}, { "HTTP_AUTHORIZATION" => "Bearer #{token}" }

    assert_equal user.id, json_body["id"]
    get_json "/api/auth/tokens"

    assert_equal ["CI"], json_body.map { |t| t["name"] }
    delete_json "/api/auth/tokens/#{json_body.first["id"]}"

    assert_status 204
  end
end
