# frozen_string_literal: true

require "json"
require "fileutils"
require "gemstack/core"
require "gemstack/schema"
require "gemstack/http"

module GemStack
  # The API contract: derived from the backend (routes + controller `accepts`
  # schemas + serializers) and emitted as TypeScript types, a typed client
  # per resource, and OpenAPI 3.1 (ARCHITECTURE §8).
  #
  #   contract = GemStack::Contract.build(GemStack.boot!)
  #   GemStack::Contract.write(contract, root: GemStack.root)
  module Contract
    class Config < Settings
      setting :output_dir, default: "frontend/lib/api/generated"
      setting :openapi_path, default: "openapi.json"
      # Import path of the client runtime from generated files.
      setting :client_import, default: "@/lib/gemstack/client"
      # Interactive API docs at <api_path>/docs, built from the live routes (development only by default).
      setting :docs, default: -> { GemStack.env.development? }
    end

    HEADER = "Generated by GemStack from the backend — do not edit. Run `gemstack contract` to regenerate."

    class << self
      def config = GemStack.config.contract

      # Builds the contract IR from a booted application (eager-loads code).
      def build(app)
        app.eager_load!
        Builder.new(routes: app.routes, api_path: app.config.http.api_path).build
      end

      # Writes TypeScript and OpenAPI files, touching only files whose content
      # changed (so Next.js doesn't hot-reload needlessly) and removing
      # generated files for resources that no longer exist. Returns
      # { written: [...], removed: [...], unchanged: [...] }. dry_run: true
      # reports what would change without touching anything (`gemstack doctor`).
      def write(contract, root:, output_dir: config.output_dir, openapi_path: config.openapi_path, typescript: true,
                dry_run: false)
        dir = File.expand_path(output_dir, root)
        files = typescript ? TypeScript.new(contract, client_import: config.client_import).files : {}
        report = { written: [], removed: [], unchanged: [] }
        files.each { |name, content| write_file(File.join(dir, name), content, report, dry_run: dry_run) }
        stale = typescript ? Dir.glob(File.join(dir, "*.ts")) : []
        stale = stale.reject { |path| files.key?(File.basename(path)) }
        stale.each do |path|
          next unless File.read(path).include?(HEADER)

          File.delete(path) unless dry_run
          report[:removed] << path
        end
        if openapi_path
          write_file(File.expand_path(openapi_path, root), "#{JSON.pretty_generate(OpenAPI.new(contract).document)}\n",
                     report, dry_run: dry_run)
        end
        report
      end

      private

      def write_file(path, content, report, dry_run: false)
        if File.exist?(path) && File.read(path) == content
          report[:unchanged] << path
          return
        end
        return report[:written] << path if dry_run

        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, content)
        report[:written] << path
      end
    end
  end

  Config.namespace(:contract, Contract::Config)
end

require_relative "contract/builder"
require_relative "contract/typescript"
require_relative "contract/openapi"
require_relative "contract/docs"

GemStack::Plugins.register(:contract_docs) do |app|
  next unless app.respond_to?(:routes) && app.config.contract.docs

  stack = app.config.http.middleware
  stack.insert_before(GemStack::HTTP::Middleware::HealthCheck, GemStack::Contract::Docs, app) unless
    stack.include?(GemStack::Contract::Docs)
end
