"use client";

// Authentication hooks (generated by `gemstack add auth`). The session lives
// in an HttpOnly cookie the browser sends automatically — JavaScript never
// sees it, so there is no token to store or leak.
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ApiError } from "@/lib/gemstack/client";
import { apiTokens, emailVerifications, passwordResets, registrations, sessions } from "@/lib/api/generated";
import type { SessionCreateInput, User } from "@/lib/api/generated";

export const authKeys = { me: ["auth", "me"] as const, tokens: ["auth", "tokens"] as const };

export type Credentials = SessionCreateInput;

/** The signed-in user, or null when signed out. */
export function useCurrentUser() {
  return useQuery({
    queryKey: authKeys.me,
    queryFn: async () => {
      try {
        return await sessions.get();
      } catch (error) {
        if (error instanceof ApiError && error.status === 401) return null;
        throw error;
      }
    },
    staleTime: 60_000,
  });
}

function useSignedIn() {
  const queryClient = useQueryClient();
  return (user: User) => {
    queryClient.setQueryData(authKeys.me, user);
    // Anything cached belonged to the previous (or no) user.
    return queryClient.invalidateQueries({ predicate: (query) => query.queryKey[0] !== "auth" });
  };
}

export function useLogin() {
  const signedIn = useSignedIn();
  return useMutation({ mutationFn: (input: Credentials) => sessions.create(input), onSuccess: signedIn });
}

export function useSignup() {
  const signedIn = useSignedIn();
  return useMutation({ mutationFn: (input: Credentials) => registrations.create(input), onSuccess: signedIn });
}

export function useLogout() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => sessions.delete(),
    onSuccess: () => {
      queryClient.clear();
      queryClient.setQueryData(authKeys.me, null);
    },
  });
}

export function useForgotPassword() {
  return useMutation({ mutationFn: (email: string) => passwordResets.create({ email }) });
}

export function useResetPassword() {
  const signedIn = useSignedIn();
  return useMutation({
    mutationFn: (input: { token: string; password: string }) => passwordResets.update(input),
    onSuccess: signedIn,
  });
}

export function useVerifyEmail() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (token: string) => emailVerifications.update({ token }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: authKeys.me }),
  });
}

export function useResendVerification() {
  return useMutation({ mutationFn: () => emailVerifications.create() });
}

export function useApiTokens() {
  return useQuery({ queryKey: authKeys.tokens, queryFn: () => apiTokens.list() });
}

export function useCreateApiToken() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (name: string) => apiTokens.create({ name }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: authKeys.tokens }),
  });
}

export function useRevokeApiToken() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: number) => apiTokens.delete(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: authKeys.tokens }),
  });
}

/** A readable message for a failed auth request. */
export function errorMessage(error: unknown): string | null {
  if (!error) return null;
  if (error instanceof ApiError) {
    const fields = Object.entries(error.errors).map(([field, messages]) => `${field} ${messages.join(", ")}`);
    return fields.length ? fields.join(". ") : error.message;
  }
  return "Something went wrong. Please try again.";
}
